#!/usr/bin/env php
<?php

chdir(dirname(dirname(realpath(__FILE__))));

file_put_contents('data_custom/modules/user_export/out.csv', '');

if (git_repos() == 'composr_homesite') {
    $issues = shell_exec('php delete_alien_files.php git_only');

    if ($issues != '') {
        echo "There seem to be files not expected in this branch, possible cleanup commands are...\n\n" . $issues;
        exit(1);
    }
}

exit(0);

function git_repos()
{
    $path = __DIR__.'/.git/HEAD';
    if (!is_file($path)) return '';
    $lines = file($path);
    $parts = explode('/', $lines[0]);
    return trim(end($parts));
}
