<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    core_cns
 */

/**
 * Hook class.
 */
class Hook_actionlog_core_cns extends Hook_actionlog
{
    /**
     * Get details of action log entry types handled by this hook. For internal use, although may be used by the base class.
     *
     * @return array Map of handler data in standard format
     */
    protected function get_handlers()
    {
        if (get_forum_type() != 'cns') {
            return array();
        }

        require_lang('cns');

        return array(
            'ADD_EMOTICON' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'emoticon',
                'identifier_index' => 0,
                'written_context_index' => 0,
                'followup_page_links' => array(
                    'EDIT_THIS_EMOTICON' => 'TODO',
                    'ADD_EMOTICON' => 'TODO',
                ),
            ),
            'EDIT_EMOTICON' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'emoticon',
                'identifier_index' => 0,
                'written_context_index' => 0,
                'followup_page_links' => array(
                    'EDIT_THIS_EMOTICON' => 'TODO',
                    'ADD_EMOTICON' => 'TODO',
                ),
            ),
            'DELETE_EMOTICON' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'emoticon',
                'identifier_index' => 0,
                'written_context_index' => 0,
                'followup_page_links' => array(
                    'ADD_EMOTICON' => 'TODO',
                ),
            ),
            'IMPORT_EMOTICONS' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => null,
                'identifier_index' => null,
                'written_context_index' => null,
                'followup_page_links' => array(
                    'EMOTICONS' => 'TODO',
                ),
            ),
            'ADD_GROUP' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'group',
                'identifier_index' => 0,
                'written_context_index' => 1,
                'followup_page_links' => array(
                    'VIEW' => 'TODO',
                    'EDIT_THIS_GROUP' => 'TODO',
                    'ADD_GROUP' => 'TODO',
                ),
            ),
            'EDIT_GROUP' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'group',
                'identifier_index' => 0,
                'written_context_index' => 1,
                'followup_page_links' => array(
                    'VIEW' => 'TODO',
                    'EDIT_THIS_GROUP' => 'TODO',
                    'ADD_GROUP' => 'TODO',
                ),
            ),
            'DELETE_GROUP' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'group',
                'identifier_index' => 0,
                'written_context_index' => 1,
                'followup_page_links' => array(
                    'ADD_GROUP' => 'TODO',
                ),
            ),
            'MEMBER_PROMOTED_AUTOMATICALLY' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'member',
                'identifier_index' => 0,
                'written_context_index' => 1,
                'followup_page_links' => array(
                    'VIEW_PROFILE' => 'TODO',
                ),
            ),
            'MEMBER_ADDED_TO_GROUP' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'member',
                'identifier_index' => 0,
                'written_context_index' => null,
                'followup_page_links' => array(
                    'VIEW_PROFILE' => 'TODO',
                    'USERGROUP' => 'TODO',
                ),
            ),
            'MEMBER_PRIMARY_GROUP_CHANGED' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'member',
                'identifier_index' => 0,
                'written_context_index' => null,
                'followup_page_links' => array(
                    'VIEW_PROFILE' => 'TODO',
                    'USERGROUP' => 'TODO',
                ),
            ),
            'MEMBER_REMOVED_FROM_GROUP' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'member',
                'identifier_index' => 0,
                'written_context_index' => null,
                'followup_page_links' => array(
                    'VIEW_PROFILE' => 'TODO',
                    'USERGROUP' => 'TODO',
                ),
            ),
            'IMPORT_MEMBER_CSV' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => null,
                'identifier_index' => null,
                'written_context_index' => null,
                'followup_page_links' => array(
                    'MEMBERS' => 'TODO',
                ),
            ),
            'DOWNLOAD_MEMBER_CSV' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => null,
                'identifier_index' => null,
                'written_context_index' => null,
                'followup_page_links' => array(
                    'MEMBERS' => 'TODO',
                ),
            ),
            'ADD_MEMBER' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'member',
                'identifier_index' => 0,
                'written_context_index' => 1,
                'followup_page_links' => array(
                    'VIEW_PROFILE' => 'TODO',
                    'ADD_MEMBER' => 'TODO',
                ),
            ),
            'EDIT_MEMBER_PROFILE' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'member',
                'identifier_index' => 0,
                'written_context_index' => 1,
                'followup_page_links' => array(
                    'VIEW_PROFILE' => 'TODO',
                ),
            ),
            'DELETE_MEMBER' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => null,
                'identifier_index' => 0,
                'written_context_index' => 1,
                'followup_page_links' => array(
                    'MEMBER_DIRECTORY' => 'TODO',
                ),
            ),
            'DELETE_LURKERS' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => null,
                'identifier_index' => null,
                'written_context_index' => null,
                'followup_page_links' => array(
                    'DELETE_LURKERS' => 'TODO',
                ),
            ),
            'MERGE_MEMBERS' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'member',
                'identifier_index' => 1,
                'written_context_index' => null,
                'followup_page_links' => array(
                    'MERGE_MEMBERS' => 'TODO',
                    'VIEW_PROFILE' => 'TODO',
                ),
            ),
            'ADD_WARNING' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => null,
                'identifier_index' => 0,
                'written_context_index' => null,
                'followup_page_links' => array(
                    'VIEW_PROFILE' => 'TODO',
                ),
            ),
            'EDIT_WARNING' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => null,
                'identifier_index' => 0,
                'written_context_index' => null,
                'followup_page_links' => array(
                    'VIEW_PROFILE' => 'TODO',
                ),
            ),
            'DELETE_WARNING' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => null,
                'identifier_index' => 0,
                'written_context_index' => null,
                'followup_page_links' => array(
                    'VIEW_PROFILE' => 'TODO',
                ),
            ),
            'BAN_MEMBER' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'member',
                'identifier_index' => 0,
                'written_context_index' => 1,
                'followup_page_links' => array(
                    'VIEW_PROFILE' => 'TODO',
                ),
            ),
            'UNBAN_MEMBER' => array(
                'flags' => ACTIONLOG_FLAGS_NONE,
                'cma_hook' => 'member',
                'identifier_index' => 0,
                'written_context_index' => 1,
                'followup_page_links' => array(
                    'VIEW_PROFILE' => 'TODO',
                ),
            ),
            'LOST_PASSWORD' => array(
                'flags' => ACTIONLOG_FLAGS_NONE | ACTIONLOG_FLAG__USER_ACTION,
                'cma_hook' => 'member',
                'identifier_index' => 0,
                'written_context_index' => null,
                'followup_page_links' => array(
                    'VIEW_PROFILE' => 'TODO',
                ),
            ),
            'RESET_PASSWORD' => array(
                'flags' => ACTIONLOG_FLAGS_NONE | ACTIONLOG_FLAG__USER_ACTION,
                'cma_hook' => 'member',
                'identifier_index' => 0,
                'written_context_index' => 1,
                'followup_page_links' => array(
                    'VIEW_PROFILE' => 'TODO',
                ),
            ),
            'EMAIL' => array(
                'flags' => ACTIONLOG_FLAGS_NONE | ACTIONLOG_FLAG__USER_ACTION,
                'cma_hook' => 'member',
                'identifier_index' => 0,
                'written_context_index' => 1,
                'followup_page_links' => array(
                    'VIEW_PROFILE' => 'TODO',
                ),
            ),
        );
    }
}
