<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    core
 */

/**
 * Hook class.
 */
class Hook_symbol_SYMBOL_DATA_AS_JSON
{
    /**
     * Run function for symbol hooks. Searches for tasks to perform.
     *
     * @param  array $param Symbol parameters
     * @return string Result
     */
    public function run($param)
    {
        require_code('symbols');
        require_code('symbols2');

        $value = array(
            'PAGE_TITLE'         => ecv_PAGE_TITLE(null, [], []),
            'MEMBER'             => ecv_MEMBER(null, [], []),
            'IS_GUEST'           => ecv_IS_GUEST(null, [], []) === '1',
            'USERNAME'           => ecv_USERNAME(null, [], []),
            'AVATAR'             => ecv_AVATAR(null, [], []),
            'MEMBER_EMAIL'       => ecv_MEMBER_EMAIL(null, [], []),
            'PHOTO'              => ecv_PHOTO(null, [], []),
            'MEMBER_PROFILE_URL' => ecv_MEMBER_PROFILE_URL(null, [], []),
            'DATE_AND_TIME'      => ecv_DATE_TIME(null, [], []),
            'DATE'               => ecv_DATE(null, [], []),
            'TIME'               => ecv_TIME(null, [], []),
            'FROM_TIMESTAMP'     => ecv_FROM_TIMESTAMP(null, [], []),
            'MOBILE'             => ecv2_MOBILE(null, [], []),
            'THEME'              => ecv2_THEME(null, [], []),
            'JS_ON'              => ecv_JS_ON(null, [], []),
            'LANG'               => ecv2_LANG(null, [], []),
            'BROWSER_UA'         => ecv2_BROWSER_UA(null, [], []),
            'OS'                 => ecv2_OS(null, [], []),
            'DEV_MODE'           => ecv_DEV_MODE(null, [], []) === '1',
            'USER_AGENT'         => ecv2_USER_AGENT(null, [], []),
            'IP_ADDRESS'         => ecv2_IP_ADDRESS(null, [], []),
            'TIMEZONE'           => ecv2_TIMEZONE(null, [], []),
            'HTTP_STATUS_CODE'   => ecv2_HTTP_STATUS_CODE(null, [], []),
            'CHARSET'            => ecv2_CHARSET(null, [], []),
            'SITE_NAME'          => ecv2_SITE_NAME(null, [], []),
            'COPYRIGHT'          => ecv2_COPYRIGHT(null, [], []),
            'DOMAIN'             => ecv2_DOMAIN(null, [], []),
            'FORUM_BASE_URL'     => ecv2_FORUM_BASE_URL(null, [], []),
            'BASE_URL'           => ecv2_BASE_URL(null, [], []),
            'BRAND_NAME'         => ecv2_BRAND_NAME(null, [], []),
            'IS_STAFF'           => ecv_IS_STAFF(null, [], []) === '1',
            'IS_ADMIN'           => ecv_IS_ADMIN(null, [], []) === '1',
            'GROUP_ID'           => ecv2_GROUP_ID(null, [], []),

        );

        return json_encode($value);
    }
}
