{$,Template is used for remote payments only; local payments use PURCHASE_WIZARD_STAGE_TRANSACT}

{+START,IF_PASSED,TEXT}
	{$PARAGRAPH,{TEXT}}
{+END}

{+START,IF_NON_PASSED,TEXT}
	<p>{!PURCHASE_STORED_DETAILS}</p>
{+END}

{LOGOS}

{TRANSACTION_BUTTON}
