{TITLE}

{+START,IF_PASSED,UNVALIDATED_PAGE_TEXT}
	<p>
		{!UNVALIDATED_PAGE_TEXT}
	</p>
{+END}

{+START,IF_NON_EMPTY,{SECTIONS}}
	{+START,INCLUDE,FORM_SCREEN_ARE_REQUIRED}{+END}

	{SECTIONS}
{+END}

{+START,IF_EMPTY,{SECTIONS}}
	<p class="nothing_here">{!NO_ENTRIES}</p>
{+END}
